version: '3'

services: 

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    #command: dockerize -wait tcp://app:3000 -timeout 40s
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
       - app

  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    command: dockerize -wait tcp://db:3306 -timeout 40s node index.js
    networks: 
      - node-network
    depends_on: 
       - db

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      